// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/types/command.proto

package types

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED  CommandType = 0
	CommandType_COMMAND_TYPE_CREATE_LEASE CommandType = 1
	CommandType_COMMAND_TYPE_RENEW_LEASE  CommandType = 2
	CommandType_COMMAND_TYPE_ACQUIRE_LOCK CommandType = 3
	CommandType_COMMAND_TYPE_RELEASE_LOCK CommandType = 4
	CommandType_COMMAND_TYPE_EXPIRE_LEASE CommandType = 5
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_UNSPECIFIED",
		1: "COMMAND_TYPE_CREATE_LEASE",
		2: "COMMAND_TYPE_RENEW_LEASE",
		3: "COMMAND_TYPE_ACQUIRE_LOCK",
		4: "COMMAND_TYPE_RELEASE_LOCK",
		5: "COMMAND_TYPE_EXPIRE_LEASE",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED":  0,
		"COMMAND_TYPE_CREATE_LEASE": 1,
		"COMMAND_TYPE_RENEW_LEASE":  2,
		"COMMAND_TYPE_ACQUIRE_LOCK": 3,
		"COMMAND_TYPE_RELEASE_LOCK": 4,
		"COMMAND_TYPE_EXPIRE_LEASE": 5,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_types_command_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_pkg_types_command_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_types_command_proto_rawDescGZIP(), []int{0}
}

// CreateLeaseCommand creates a new lease
type CreateLeaseCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	TtlNanos      int64                  `protobuf:"varint,2,opt,name=ttl_nanos,json=ttlNanos,proto3" json:"ttl_nanos,omitempty"` // Duration in nanoseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLeaseCommand) Reset() {
	*x = CreateLeaseCommand{}
	mi := &file_pkg_types_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLeaseCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLeaseCommand) ProtoMessage() {}

func (x *CreateLeaseCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_types_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLeaseCommand.ProtoReflect.Descriptor instead.
func (*CreateLeaseCommand) Descriptor() ([]byte, []int) {
	return file_pkg_types_command_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLeaseCommand) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateLeaseCommand) GetTtlNanos() int64 {
	if x != nil {
		return x.TtlNanos
	}
	return 0
}

// RenewLeaseCommand renews an existing lease
type RenewLeaseCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       uint64                 `protobuf:"varint,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewLeaseCommand) Reset() {
	*x = RenewLeaseCommand{}
	mi := &file_pkg_types_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewLeaseCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewLeaseCommand) ProtoMessage() {}

func (x *RenewLeaseCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_types_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewLeaseCommand.ProtoReflect.Descriptor instead.
func (*RenewLeaseCommand) Descriptor() ([]byte, []int) {
	return file_pkg_types_command_proto_rawDescGZIP(), []int{1}
}

func (x *RenewLeaseCommand) GetLeaseId() uint64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

// AcquireLockCommand acquires a lock with fencing
type AcquireLockCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockName      string                 `protobuf:"bytes,1,opt,name=lock_name,json=lockName,proto3" json:"lock_name,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	LeaseId       uint64                 `protobuf:"varint,3,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireLockCommand) Reset() {
	*x = AcquireLockCommand{}
	mi := &file_pkg_types_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireLockCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireLockCommand) ProtoMessage() {}

func (x *AcquireLockCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_types_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireLockCommand.ProtoReflect.Descriptor instead.
func (*AcquireLockCommand) Descriptor() ([]byte, []int) {
	return file_pkg_types_command_proto_rawDescGZIP(), []int{2}
}

func (x *AcquireLockCommand) GetLockName() string {
	if x != nil {
		return x.LockName
	}
	return ""
}

func (x *AcquireLockCommand) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *AcquireLockCommand) GetLeaseId() uint64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

// ReleaseLockCommand releases a lock
type ReleaseLockCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LockName      string                 `protobuf:"bytes,1,opt,name=lock_name,json=lockName,proto3" json:"lock_name,omitempty"`
	LeaseId       uint64                 `protobuf:"varint,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseLockCommand) Reset() {
	*x = ReleaseLockCommand{}
	mi := &file_pkg_types_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseLockCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseLockCommand) ProtoMessage() {}

func (x *ReleaseLockCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_types_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseLockCommand.ProtoReflect.Descriptor instead.
func (*ReleaseLockCommand) Descriptor() ([]byte, []int) {
	return file_pkg_types_command_proto_rawDescGZIP(), []int{3}
}

func (x *ReleaseLockCommand) GetLockName() string {
	if x != nil {
		return x.LockName
	}
	return ""
}

func (x *ReleaseLockCommand) GetLeaseId() uint64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

// ExpireLeaseCommand expires a lease and releases all its locks
type ExpireLeaseCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       uint64                 `protobuf:"varint,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpireLeaseCommand) Reset() {
	*x = ExpireLeaseCommand{}
	mi := &file_pkg_types_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpireLeaseCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireLeaseCommand) ProtoMessage() {}

func (x *ExpireLeaseCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_types_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireLeaseCommand.ProtoReflect.Descriptor instead.
func (*ExpireLeaseCommand) Descriptor() ([]byte, []int) {
	return file_pkg_types_command_proto_rawDescGZIP(), []int{4}
}

func (x *ExpireLeaseCommand) GetLeaseId() uint64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

// CommandWrapper wraps any command for serialization
type CommandWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  CommandType            `protobuf:"varint,1,opt,name=type,proto3,enum=types.CommandType" json:"type,omitempty"`
	// Only one of these will be set based on type
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*CommandWrapper_CreateLease
	//	*CommandWrapper_RenewLease
	//	*CommandWrapper_AcquireLock
	//	*CommandWrapper_ReleaseLock
	//	*CommandWrapper_ExpireLease
	Payload       isCommandWrapper_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandWrapper) Reset() {
	*x = CommandWrapper{}
	mi := &file_pkg_types_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandWrapper) ProtoMessage() {}

func (x *CommandWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_types_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandWrapper.ProtoReflect.Descriptor instead.
func (*CommandWrapper) Descriptor() ([]byte, []int) {
	return file_pkg_types_command_proto_rawDescGZIP(), []int{5}
}

func (x *CommandWrapper) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *CommandWrapper) GetPayload() isCommandWrapper_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CommandWrapper) GetCreateLease() *CreateLeaseCommand {
	if x != nil {
		if x, ok := x.Payload.(*CommandWrapper_CreateLease); ok {
			return x.CreateLease
		}
	}
	return nil
}

func (x *CommandWrapper) GetRenewLease() *RenewLeaseCommand {
	if x != nil {
		if x, ok := x.Payload.(*CommandWrapper_RenewLease); ok {
			return x.RenewLease
		}
	}
	return nil
}

func (x *CommandWrapper) GetAcquireLock() *AcquireLockCommand {
	if x != nil {
		if x, ok := x.Payload.(*CommandWrapper_AcquireLock); ok {
			return x.AcquireLock
		}
	}
	return nil
}

func (x *CommandWrapper) GetReleaseLock() *ReleaseLockCommand {
	if x != nil {
		if x, ok := x.Payload.(*CommandWrapper_ReleaseLock); ok {
			return x.ReleaseLock
		}
	}
	return nil
}

func (x *CommandWrapper) GetExpireLease() *ExpireLeaseCommand {
	if x != nil {
		if x, ok := x.Payload.(*CommandWrapper_ExpireLease); ok {
			return x.ExpireLease
		}
	}
	return nil
}

type isCommandWrapper_Payload interface {
	isCommandWrapper_Payload()
}

type CommandWrapper_CreateLease struct {
	CreateLease *CreateLeaseCommand `protobuf:"bytes,2,opt,name=create_lease,json=createLease,proto3,oneof"`
}

type CommandWrapper_RenewLease struct {
	RenewLease *RenewLeaseCommand `protobuf:"bytes,3,opt,name=renew_lease,json=renewLease,proto3,oneof"`
}

type CommandWrapper_AcquireLock struct {
	AcquireLock *AcquireLockCommand `protobuf:"bytes,4,opt,name=acquire_lock,json=acquireLock,proto3,oneof"`
}

type CommandWrapper_ReleaseLock struct {
	ReleaseLock *ReleaseLockCommand `protobuf:"bytes,5,opt,name=release_lock,json=releaseLock,proto3,oneof"`
}

type CommandWrapper_ExpireLease struct {
	ExpireLease *ExpireLeaseCommand `protobuf:"bytes,6,opt,name=expire_lease,json=expireLease,proto3,oneof"`
}

func (*CommandWrapper_CreateLease) isCommandWrapper_Payload() {}

func (*CommandWrapper_RenewLease) isCommandWrapper_Payload() {}

func (*CommandWrapper_AcquireLock) isCommandWrapper_Payload() {}

func (*CommandWrapper_ReleaseLock) isCommandWrapper_Payload() {}

func (*CommandWrapper_ExpireLease) isCommandWrapper_Payload() {}

var File_pkg_types_command_proto protoreflect.FileDescriptor

const file_pkg_types_command_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/types/command.proto\x12\x05types\"L\n" +
	"\x12CreateLeaseCommand\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1b\n" +
	"\tttl_nanos\x18\x02 \x01(\x03R\bttlNanos\".\n" +
	"\x11RenewLeaseCommand\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\x04R\aleaseId\"g\n" +
	"\x12AcquireLockCommand\x12\x1b\n" +
	"\tlock_name\x18\x01 \x01(\tR\blockName\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x19\n" +
	"\blease_id\x18\x03 \x01(\x04R\aleaseId\"L\n" +
	"\x12ReleaseLockCommand\x12\x1b\n" +
	"\tlock_name\x18\x01 \x01(\tR\blockName\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\x04R\aleaseId\"/\n" +
	"\x12ExpireLeaseCommand\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\x04R\aleaseId\"\x80\x03\n" +
	"\x0eCommandWrapper\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.types.CommandTypeR\x04type\x12>\n" +
	"\fcreate_lease\x18\x02 \x01(\v2\x19.types.CreateLeaseCommandH\x00R\vcreateLease\x12;\n" +
	"\vrenew_lease\x18\x03 \x01(\v2\x18.types.RenewLeaseCommandH\x00R\n" +
	"renewLease\x12>\n" +
	"\facquire_lock\x18\x04 \x01(\v2\x19.types.AcquireLockCommandH\x00R\vacquireLock\x12>\n" +
	"\frelease_lock\x18\x05 \x01(\v2\x19.types.ReleaseLockCommandH\x00R\vreleaseLock\x12>\n" +
	"\fexpire_lease\x18\x06 \x01(\v2\x19.types.ExpireLeaseCommandH\x00R\vexpireLeaseB\t\n" +
	"\apayload*\xc5\x01\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19COMMAND_TYPE_CREATE_LEASE\x10\x01\x12\x1c\n" +
	"\x18COMMAND_TYPE_RENEW_LEASE\x10\x02\x12\x1d\n" +
	"\x19COMMAND_TYPE_ACQUIRE_LOCK\x10\x03\x12\x1d\n" +
	"\x19COMMAND_TYPE_RELEASE_LOCK\x10\x04\x12\x1d\n" +
	"\x19COMMAND_TYPE_EXPIRE_LEASE\x10\x05B%Z#github.com/pixperk/lowkey/pkg/typesb\x06proto3"

var (
	file_pkg_types_command_proto_rawDescOnce sync.Once
	file_pkg_types_command_proto_rawDescData []byte
)

func file_pkg_types_command_proto_rawDescGZIP() []byte {
	file_pkg_types_command_proto_rawDescOnce.Do(func() {
		file_pkg_types_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_types_command_proto_rawDesc), len(file_pkg_types_command_proto_rawDesc)))
	})
	return file_pkg_types_command_proto_rawDescData
}

var file_pkg_types_command_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_types_command_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_types_command_proto_goTypes = []any{
	(CommandType)(0),           // 0: types.CommandType
	(*CreateLeaseCommand)(nil), // 1: types.CreateLeaseCommand
	(*RenewLeaseCommand)(nil),  // 2: types.RenewLeaseCommand
	(*AcquireLockCommand)(nil), // 3: types.AcquireLockCommand
	(*ReleaseLockCommand)(nil), // 4: types.ReleaseLockCommand
	(*ExpireLeaseCommand)(nil), // 5: types.ExpireLeaseCommand
	(*CommandWrapper)(nil),     // 6: types.CommandWrapper
}
var file_pkg_types_command_proto_depIdxs = []int32{
	0, // 0: types.CommandWrapper.type:type_name -> types.CommandType
	1, // 1: types.CommandWrapper.create_lease:type_name -> types.CreateLeaseCommand
	2, // 2: types.CommandWrapper.renew_lease:type_name -> types.RenewLeaseCommand
	3, // 3: types.CommandWrapper.acquire_lock:type_name -> types.AcquireLockCommand
	4, // 4: types.CommandWrapper.release_lock:type_name -> types.ReleaseLockCommand
	5, // 5: types.CommandWrapper.expire_lease:type_name -> types.ExpireLeaseCommand
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_types_command_proto_init() }
func file_pkg_types_command_proto_init() {
	if File_pkg_types_command_proto != nil {
		return
	}
	file_pkg_types_command_proto_msgTypes[5].OneofWrappers = []any{
		(*CommandWrapper_CreateLease)(nil),
		(*CommandWrapper_RenewLease)(nil),
		(*CommandWrapper_AcquireLock)(nil),
		(*CommandWrapper_ReleaseLock)(nil),
		(*CommandWrapper_ExpireLease)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_types_command_proto_rawDesc), len(file_pkg_types_command_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_types_command_proto_goTypes,
		DependencyIndexes: file_pkg_types_command_proto_depIdxs,
		EnumInfos:         file_pkg_types_command_proto_enumTypes,
		MessageInfos:      file_pkg_types_command_proto_msgTypes,
	}.Build()
	File_pkg_types_command_proto = out.File
	file_pkg_types_command_proto_goTypes = nil
	file_pkg_types_command_proto_depIdxs = nil
}
